### PR TITLE
Fix: Redirecting wrong urls to home and un authorized uls to login page.

### LINKED ISSUE #25: 404 when not logged in
going to the /climbs page should redirect to the login page and not 404

### PR DESCRIPTION
**Pull request by apchandu96**
If the route is valid and does not have token or authorization it will direct to login page
image

If there is no route and If you are trying to access it through URL this will  take you to home page. In you case there is no route to **climbs** only climb is valid route. Therefore when user enters **climbs** which is not a valid URL this is take you to base URL which is home page.
image

Please let me know if this is something you are looking for or let me know anything else. I can amend the changes 

Closes: https://github.com/nicholasbergesen/boulderlog/issues/25

### CODE REVIEW

File: boulderlog/Program.cs [hunk 1]
```diff
@@ -147,6 +147,19 @@ public static void Main(string[] args)
...
+              await next();
+
+            if (context.Response.StatusCode == 404)
+            {
+                 context.Response.Redirect("/"); //Redirecting if wrong url or wrong route is added
+            }
+            else if (!context.User.Identity.IsAuthenticated)
+            {
+                 context.Response.Redirect("Identity/Account/Login");
+            }
```
Comment (nicholasbergesen) [inline boulderlog/Program.cs]:
```suggestion
```

Hi @apchandu96, I did some testing, and it appears the auth routes already redirect the login page. Thank you again for this contribution, I'll approve the pr once you update this change to take out the login redirect.

Apologies for the information logged in the [404 issue](https://github.com/nicholasbergesen/boulderlog/issues/25), it was quite misleading, thank you for sticking with it :)

**Review by nicholasbergesen — CHANGES_REQUESTED** [review]

**Review by nicholasbergesen — APPROVED** [review]

**Comment by nicholasbergesen** [comment]
Approved, feel free to merge in the PR.
